#!/usr/bin/env bash
set -e
cd "$(realpath "$(dirname "$(realpath "$0")")/..")"

. scripts/make-build

version=$(grep -Pzo '(?s)__version__ = "\K.*?(?=")' "src/dynapi/__version__.py" | tr -d '\0')

cp scripts/extra/dynapi.service build/dynapi/

echo "Created archive of build..."
cd build
tar -czf dynapi-"${version}".tgz dynapi/
cd ..
