#!/usr/bin/env bash
set -e
cd "$(realpath "$(dirname "$(realpath "$0")")/..")"

# create build directory
mkdir -p "build/"
[ -d "build/dynapi/" ] && rm -rf "build/dynapi/"

# copy source code
echo "Copying code..."
cp -Lr "src/dynapi/" "build/dynapi/"
cp README.md "build/dynapi/"

# cleanup of copied
find build/dynapi -type d -iname __pycache__ -prune -exec rm -rf "{}" \;
[ -f "build/dynapi/api.conf" ] && rm "build/dynapi/api.conf"
mkdir -p "build/dynapi/plugins/"

# install dependencies into (new) copied source-code directory
echo "Installing dependencies..."
python3 -m pip install -q -r "requirements-names.txt" -t "build/dynapi/" --compile --disable-pip-version-check
rm -rf build/dynapi/*.dist-info

echo "Installing scripts..."
echo "Build for $(python3 -V)
OS Detail:
$(sed 's/^/ /' /etc/os-release)
" > "build/dynapi/meta.info"
cp "scripts/extra/dynapi.run.sh" "build/dynapi/dynapi.run"
chmod +x "build/dynapi/dynapi.run"

#echo "Opimizations..."
#python3 -m compileall "build/dynapi/" -b -q
#find build/dynapi -name "*.py" -type f -delete
#pyminify build/dynapi --in-place

echo "Build successful"
